//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int id_added { get; set; }
        public string product_name { get; set; }
        public string calories_gram { get; set; }
        public string proteins_gram { get; set; }
        public string fats_gram { get; set; }
        public string carbohydrated_gram { get; set; }
    }
}
