//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearShop.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WearShop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new product.
        /// </summary>
        public static string AddNewProductTitle {
            get {
                return ResourceManager.GetString("AddNewProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add product.
        /// </summary>
        public static string AddOneBTTN {
            get {
                return ResourceManager.GetString("AddOneBTTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add picture.
        /// </summary>
        public static string AddPictureBTTN {
            get {
                return ResourceManager.GetString("AddPictureBTTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CancelBTTN {
            get {
                return ResourceManager.GetString("CancelBTTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category.
        /// </summary>
        public static string CategoryCB {
            get {
                return ResourceManager.GetString("CategoryCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clothes.
        /// </summary>
        public static string Clothes {
            get {
                return ResourceManager.GetString("Clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color:.
        /// </summary>
        public static string Color_ {
            get {
                return ResourceManager.GetString("Color_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Black.
        /// </summary>
        public static string ColorBlack {
            get {
                return ResourceManager.GetString("ColorBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blue.
        /// </summary>
        public static string ColorBlue {
            get {
                return ResourceManager.GetString("ColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brown.
        /// </summary>
        public static string ColorBrown {
            get {
                return ResourceManager.GetString("ColorBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cyan.
        /// </summary>
        public static string ColorCyan {
            get {
                return ResourceManager.GetString("ColorCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Green.
        /// </summary>
        public static string ColorGreen {
            get {
                return ResourceManager.GetString("ColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Orange.
        /// </summary>
        public static string ColorOrange {
            get {
                return ResourceManager.GetString("ColorOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pink.
        /// </summary>
        public static string ColorPink {
            get {
                return ResourceManager.GetString("ColorPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Red.
        /// </summary>
        public static string ColorRed {
            get {
                return ResourceManager.GetString("ColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yellow.
        /// </summary>
        public static string ColorYellow {
            get {
                return ResourceManager.GetString("ColorYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cost:.
        /// </summary>
        public static string Cost_ {
            get {
                return ResourceManager.GetString("Cost_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cost.
        /// </summary>
        public static string CostTB {
            get {
                return ResourceManager.GetString("CostTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string DeleteBTTN {
            get {
                return ResourceManager.GetString("DeleteBTTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string DescriptionTB {
            get {
                return ResourceManager.GetString("DescriptionTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string EditBTTN {
            get {
                return ResourceManager.GetString("EditBTTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full name.
        /// </summary>
        public static string FullNameTB {
            get {
                return ResourceManager.GetString("FullNameTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string OkBTTN {
            get {
                return ResourceManager.GetString("OkBTTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rate:.
        /// </summary>
        public static string Rate_ {
            get {
                return ResourceManager.GetString("Rate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shoes.
        /// </summary>
        public static string Shoes {
            get {
                return ResourceManager.GetString("Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Short name.
        /// </summary>
        public static string ShortNameTB {
            get {
                return ResourceManager.GetString("ShortNameTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size:.
        /// </summary>
        public static string Size_ {
            get {
                return ResourceManager.GetString("Size_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size.
        /// </summary>
        public static string SizeTB {
            get {
                return ResourceManager.GetString("SizeTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filtration.
        /// </summary>
        public static string StartFilterBTTN {
            get {
                return ResourceManager.GetString("StartFilterBTTN", resourceCulture);
            }
        }
    }
}
