//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_PARAMS
    {
        public int id_params { get; set; }
        public System.DateTime params_date { get; set; }
        public decimal user_weight { get; set; }
        public int user_height { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
