//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_DATA
    {
        public int id_data { get; set; }
        public string full_name { get; set; }
        public System.DateTime birthday { get; set; }
        public int age { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
