//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTS
    {
        public int id_report { get; set; }
        public System.DateTime report_date { get; set; }
        public string eat_period { get; set; }
        public decimal day_calories { get; set; }
        public decimal day_proteins { get; set; }
        public decimal day_fats { get; set; }
        public decimal day_carbohydrates { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
